In [9]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)  


[1 2 3 4 5]


In [10]:
import numpy as np


sales_data = np.array([
    [[250, 300, 400], [200, 250, 350]],  
    [[260, 310, 410], [210, 260, 360]],  
    [[270, 320, 420], [220, 270, 370]], 
    [[280, 330, 430], [230, 280, 380]]   
])

print("3D Array:\n", sales_data)
print("Shape:", sales_data.shape)  arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)  



3D Array:
 [[[250 300 400]
  [200 250 350]]

 [[260 310 410]
  [210 260 360]]

 [[270 320 420]
  [220 270 370]]

 [[280 330 430]
  [230 280 380]]]
Shape: (4, 2, 3)


In [11]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)  



[[1 2 3]
 [4 5 6]]


In [12]:
zeros = np.zeros((2, 3))
print(zeros)  



[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
ones = np.ones((3, 2))
print(ones)  



[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [14]:
range_array = np.arange(10)
print(range_array)  


[0 1 2 3 4 5 6 7 8 9]


In [15]:
range_step = np.arange(0, 10, 2)
print(range_step)  


[0 2 4 6 8]


In [16]:
linspace_array = np.linspace(0, 1, 5)
print(linspace_array) 


[0.   0.25 0.5  0.75 1.  ]


In [17]:
random_array = np.random.rand(3, 3)
print(random_array)


[[0.34852387 0.28584757 0.66304118]
 [0.85565824 0.69415564 0.36345838]
 [0.37244408 0.00588113 0.60569806]]


In [18]:
random_integers = np.random.randint(1, 10, (2, 2))
print(random_integers)


[[2 3]
 [9 7]]


In [22]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape) 


(2, 3)


In [23]:
print (arr.dtype)


int32


In [24]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])   
print(arr[-1])  


10
50


In [25]:
print(arr[1:4])

[20 30 40]


In [9]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[0, 2]) 

3


In [3]:
# mat = [row, col]
# mat = [row][col]


In [10]:
mat = np.array([[5, 10, 20], [20, 25, 30], [35, 40, 10]])
print(mat)  


[[ 5 10 20]
 [20 25 30]
 [35 40 10]]


In [16]:
mat[1]  


array([20, 25, 30])

In [17]:
mat[2]


array([35, 40, 10])

In [19]:
mat[1][1]
 

25

In [18]:
mat[1, 2]
 

30

In [20]:
mat

array([[ 5, 10, 20],
       [20, 25, 30],
       [35, 40, 10]])

In [21]:
mat[0]


array([ 5, 10, 20])

In [22]:
mat[:2,1:]

array([[10, 20],
       [25, 30]])

In [23]:
mat[1:,:2]


array([[20, 25],
       [35, 40]])

In [24]:
mat[2]


array([35, 40, 10])

In [25]:
mat[2,:]

array([35, 40, 10])

In [26]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], 
              [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [27]:
a[1, 5] 

13

In [28]:
a[0, :] 

array([1, 2, 3, 4, 5, 6, 7])

In [29]:
a[:, 2] 

array([ 3, 10])

In [30]:
a[0, 1:-1:2]


array([2, 4, 6])

In [31]:
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
a > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [35]:
bool_a = a > 4
bool_a

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [34]:
a[bool_a]

array([ 5,  6,  7,  8,  9, 10])

In [36]:
a[a > 2]


array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)  


[5 7 9]


In [38]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [39]:
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [40]:
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [41]:
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [42]:
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [43]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [45]:
f = np.array([1,2])
g = np.array([4,5])
np.dot(f, g)

14

In [47]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr + 10) 
                 




[[11 12 13]
 [14 15 16]]


In [49]:
import numpy as np

prices = [10, 20, 30, 40]  
prices_array = np.array(prices)  
updated_prices = prices_array * 1.1  

print(updated_prices)



[11. 22. 33. 44.]


In [50]:
import numpy as np

# Define matrix and vector
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 2, 1])  # Vector

# Using broadcasting for efficient computation
y = x + v

print("Original Matrix (x):")
print(x)
print("=================")
print("Updated Matrix (y = x + v):")
print(y)


Original Matrix (x):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Updated Matrix (y = x + v):
[[ 2  4  4]
 [ 5  7  7]
 [ 8 10 10]
 [11 13 13]]


In [51]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])


result = np.dot(arr1, arr2)

print(result)


[[19 22]
 [43 50]]


In [52]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(np.mean(arr))
print(np.sum(arr)) 


3.0
15


In [53]:
print (np.max (arr))
print (np.min (arr))

5
1


In [1]:
#Task 1: Slicing
import numpy as np

matrix = np.arange(1, 31).reshape(6, 5)
print(matrix)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [4]:
sub_matrix3 = matrix[[0, 4, 5], 3:5]
print(sub_matrix3)


[[ 4  5]
 [24 25]
 [29 30]]


In [5]:
sub_matrix1 = matrix[2:4, 0:2]
print(sub_matrix1)


[[11 12]
 [16 17]]


In [7]:
sub_matrix2 = matrix[[0, 2, 3, 4], 1]
print(sub_matrix2)



[ 2 12 17 22]
